version: '3.7'

services:
    web:
        env_file:
            - .env
        build: .
        command:
            - /bin/bash
            - -c
            - python3 /code/rilufab.py

        volumes:
            - .:/code


