name: Fakegato


on: push

  #  schedule:

    #    - cron: '45 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se você tiver um arquivo requirements.txt com as dependências

    - name: Run the fakecat script
      env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}

                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}

                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
   
      run: python fakecat.py
